site_name: Simplicity
site_url: https://docs.simplicity-lang.org/
site_description: A typed, combinator-based, functional smart contract language without loops or recursion, designed for Bitcoin-like blockchains.
plugins:
  - search:
  - git-revision-date-localized:
  - ezglossary:
     tooltip: full
     ignore_case: true
  # add this back in when we have more authors
  # - git-committers:
  #     repository: BlockstreamResearch/simplicity-lang-org
  #     branch: main
theme:
  name: material
  custom_dir: overrides
  favicon: assets/logo-symbol.svg
  logo: assets/logo-symbol.svg
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black # fallback, overridden by CSS
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - attr_list:
  - md_in_html:
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: youtube
          class: youtube
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition:
  - pymdownx.details:
  - pymdownx.tabbed:
      alternate_style: true
  - tables:
  - def_list:
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@Blockstream/search?query=simplicity
    - icon: simple/telegram
      link: https://t.me/simplicity_community
    - icon: fontawesome/brands/github
      link: https://github.com/BlockstreamResearch/simplicity
    - icon: fontawesome/brands/rust
      link: https://crates.io/crates/simplicity
    - icon: material/chat 
      link: https://matrix.to/#/#libera_##simplicity:bitcoin.ninja
    - icon: material/chat
      link: irc://irc.libera.chat/simplicity
  analytics:
    provider: google
    property: G-CPMC9XLPYJ
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-


            Thanks for your feedback! Help us improve this page by
            logging a documentation <a href="https://github.com/BlockstreamResearch/simplicity-lang-org/issues/new?body=I%20would%20like%20to%20improve%20the%20Simplicity%20documentation%20&labels=documentation&title=documentation%20fix:%20" target="_blank" rel="noopener">issue</a>.

copyright: Copyright &copy; 2025 Blockstream

repo_url: https://github.com/BlockstreamResearch/simplicity-lang-org
repo_name: "" # Hides the GitHub link/icon from title bar while keeping edit functionality
edit_uri: edit/main/docs/

nav:
  - Getting started:
      - index.md
      - Quickstart: getting-started/quickstart.md
      - Tools & Projects: getting-started/projects.md
#      - SimplicityHL: getting-started/simplicityhl.md
      - Web IDE: getting-started/web-ide.md
#      - CLI Guide: getting-started/cli.md
#      - Rust: getting-started/rust.md
#      - Haskell: getting-started/haskell.md
  - Documentation:
      - How Simplicity Works: documentation/how-simplicity-works.md
      - Execution Model: documentation/execution-model.md
      - Witnesses in SimplicityHL Development: documentation/witness.md
      - Whitepaper: https://blockstream.com/simplicity.pdf
      - Technical Report: https://raw.githubusercontent.com/ElementsProject/simplicity/pdf/Simplicity-TR.pdf
      - Glossary: glossary.md
      - Jets Reference: documentation/jets.md
      - Jets Explained: documentation/jets-explained.md
      - Simplicity for EVM developers: documentation/simplicity-for-evm-developers.md
      - Simplicity Compared: documentation/simplicity-compared.md
      - Differences from Rust: documentation/rust-differences.md
      - Examples: https://github.com/BlockstreamResearch/SimplicityHL/tree/master/examples
  - SimplicityHL Reference:
      - simplicityhl-reference/index.md
      - Types and Values: simplicityhl-reference/type.md
      - Type Aliases: simplicityhl-reference/type_alias.md
      - Type Casting: simplicityhl-reference/type_casting.md
      - Let Statements: simplicityhl-reference/let_statement.md
      - Match Expression: simplicityhl-reference/match_expression.md
      - Functions: simplicityhl-reference/function.md
      - Programs: simplicityhl-reference/program.md
      - Context: simplicityhl-reference/context.md
      - State Management: documentation/state.md
      - Environment: simplicityhl-reference/environment.md
      - Translation: simplicityhl-reference/translation.md
#  Remove until we have content
  - Use Cases:
      - use-cases/index.md
      - Simplicity DEX: use-cases/simplicity-dex.md
#      - Simplicty Unchained: use-cases/unchained.md
#      - Financial Contracts: use-cases/financial-contracts.md
#      - Discreet Log Contracts: use-cases/discreet-log-contracts.md
#      - Cross-Chain Atomic Swaps: use-cases/cross-chain-atomic-swaps.md
#      - Crowdfunding Contracts: use-cases/crowdfunding.md
#      - Vaults: use-cases/vaults.md
#      - Insurance Contracts: use-cases/insurance-contracts.md
  - Resources:
      - Roadmap: resources/roadmap.md
      - FAQ: resources/faq.md
      - Contribute: resources/contribute.md
  - Office Hours:
       - Join our Weekly Office Hours: office-hours.md
